### ISSUE TITLE
Detectar settings do game automaticamente

### ISSUE THREAD

**Issue by jpvolt** [Setti7/SVFB-GUI#36]

**Comment by jpvolt** [comment]
commit 911dc5d

**Comment by Setti7** [comment]
Mano detectar o peixe é furada. Já tentei fazer isso no começo e dá muito erro. Testei seu código e ele funciona, mas fica quebrando o sessão em vários pedaços pequenos pq tem um ou outro frame que ele não consegue capturar direito. Isso não pode acontecer porque o programa precisa enviar o arquivo da sessão inteira direto pro servidor.

**Comment by Setti7** [comment]
Mas a sua ideia do autozoom eu achei muito boa. Só acho que ela seria melhor ao achar a area de pesca e não só o peixe (o peixe dá muito falso positivo por ser muito pequeno e o threshold ter que ser baixo)

**Comment by Setti7** [comment]
Eu fiz uma analise do tamanho da região que eu tava fazendo template matching em relação ao zoom. Ou seja, tava tentando descobrir se havia uma relação linear entre o zoom e a área. O que eu descobri é que não é perfeitamente linear (o nível de zoom -3 é diferente dos outros)
