### ISSUE TITLE
BUG: Botão send data fica habilitado quando para de treinar

### ISSUE THREAD

**Issue by jpvolt** [Setti7/SVFB-GUI#37]
BUG: Botão send data fica habilitado quando para de treinar, mesmo que já esteja mandando o arquivo, se clicar nele o programa crasha
![image](https://user-images.githubusercontent.com/12127137/43302527-7e02ef32-9141-11e8-8478-c37e5c3fc6f1.png)
Erro do crash:
![image](https://user-images.githubusercontent.com/12127137/43302550-aade401a-9141-11e8-9423-3210136caf08.png)

**Comment by Setti7** [comment]
Vc mexeu no senddata? Isso não acontecia antes
